config/routes.rb
Rails.application.routes.draw do


  resources :conversations, only: [:index,:create,:new] do
    resources :messages, only: [:index,:create]
  end

  get 'communities/:community/events' => 'events#index', as: 'community_events'
  get 'communities/:community_id/contacts/preview' => "contacts#preview", as: 'community_contact_preview'
  resources :badge_rules
  get 'badges/:uuid/claim' => "badges#claim", as: 'badge_claim'
  get 'badges/:uuid/qrcode' => "badges#qrcode", as: 'qrcode_badge'
  get 'badges/:id/assertion' => "badges#assertion", as: 'badge_assertion'
  resources :badges
  resources :attendees
  resources :tickets
  resources :ticket_types

  resources :notifications, only: [:index]
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/badges/:event_id" => "badges#index", as: "event_badges"
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  #get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  #get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  get 'users/:id/badges' => 'user#assertions', as: 'user_badges'
  get 'users/events' => 'user#events', as: 'my_events'

  post 'events/:id/unique' => 'events#unique', as: 'unique_event'
  post 'events/unique' => 'events#unique', as: 'new_unique_event'
  post 'events/:event_id/attendees/draw' => 'attendees#draw', as: 'draw_attendees'

  resources :events do
    resources :attendees, only: [:index]
    resources :schedule, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities do
    resources :members
    resources :invites
    resources :boards do
      resources :board_messages, only: [:new,:edit,:show,:update,:create,:destroy]
    end
    resources :contacts
  end
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/carousel.rb
class Carousel < ApplicationRecord
  belongs_to :user
  belongs_to :page
  has_paper_trail
  has_attached_file :image, styles: { carousel: "1200x500", medium: "300x300>", thumb: "100x100>" },
    :processors => [:cropper],
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  attr_accessor :crop_x, :crop_y, :crop_x2, :crop_y2, :crop_w, :crop_h, :crop_vy
  after_update :reprocess_image, :if => :cropping?
  after_create :reprocess_image, :if => :cropping?

  private

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def image_geometry(style = :original)
    tmpfile = image.queued_for_write[style]
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(tmpfile)
  end

  def reprocess_image
    image_geometry(:original)
    self.crop_h = 500
    self.crop_w = 1200
    self.crop_y = (@geometry[:original].height.to_f * (self.crop_y.to_f / self.crop_vy.to_f)).to_i
    self.crop_x = (@geometry[:original].width.to_f * (self.crop_x.to_f / 1100.to_f)).to_i
    image.assign(image)
    image.save
  end

end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_carousel, only: [:show, :edit, :update, :destroy]

  # GET /carousels
  # GET /carousels.json
  def index
    @carousels = Carousel.all
  end

  # GET /carousels/1
  # GET /carousels/1.json
  def show
  end

  # GET /carousels/new
  def new
    @carousel = Carousel.new
  end

  # GET /carousels/1/edit
  def edit
  end

  # POST /carousels
  # POST /carousels.json
  def create
    @carousel = current_user.carousels.new(carousel_params)

    respond_to do |format|
      if @carousel.save
        format.html { redirect_to @carousel, notice: 'Carousel was successfully created.' }
        format.json { render :show, status: :created, location: @carousel }
      else
        format.html { render :new }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carousels/1
  # PATCH/PUT /carousels/1.json
  def update
    respond_to do |format|
      if @carousel.update(carousel_params)
        format.html { redirect_to @carousel, notice: 'Carousel was successfully updated.' }
        format.json { render :show, status: :ok, location: @carousel }
      else
        format.html { render :edit }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carousels/1
  # DELETE /carousels/1.json
  def destroy
    @carousel.destroy
    respond_to do |format|
      format.html { redirect_to carousels_url, notice: 'Carousel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carousel
      @carousel = Carousel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carousel_params
      params.require(:carousel).permit(:user_id, :header, :sentence, :link, :image, :page_id, :active, :crop_x, :crop_y, :crop_x2, :crop_y2, :crop_w, :crop_h, :crop_vy)
    end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/views/carousels/_form.html.slim
= form_for @carousel do |f|
  - if @carousel.errors.any?
    #error_explanation
    div class="form-group"
      h2 = "#{pluralize(@carousel.errors.count, "error")} prohibited this carousel from being saved:"
      ul
        - @carousel.errors.full_messages.each do |message|
          li = message

  div class="form-group"
    = f.label t(:header), class: "form-input-label"
    = f.text_field :header, class: "form-control"
  div class="form-group"
    = f.label t(:sentence), class: "form-input-label"
    = f.text_field :sentence, class: "form-control"
  div class="form-group"
    = f.label t(:link), class: "form-input-label"
    = f.text_field :link, class: "form-control"
  div class="form-group"
    = f.label t(:image), class: "form-input-label"
    - %w[x y x2 y2 w h vy].each do |attribute|
       = f.hidden_field "crop_#{attribute}", id: "crop_#{attribute}"
    div id="carouselPreview" class="text-center"
     - if params[:action]==="edit"
        div class="thumbnail"
          = image_tag @carousel.image.url, id: "carouselimage"
    = f.file_field :image, class: "form-control-file"
  div class="form-group"
    = f.label t(:page), class: "form-input-label"
    | :&nbsp;
    = f.select :page_id, Page.all.collect {|p| [p.title, p.id]}, class: "form-control"
  div class="form-check"
    = f.check_box :active, class: "form-check-input"
    | &nbsp;
    = f.label t(:active), class: "form-input-label"
  div class="form-group"
    = f.submit t(:save),  class: "btn btn-primary"

app/views/carousels/edit.html.slim
div class="container"
     div class="col-lg-12"
       div class="page-header"
         h3 class="display-3"
           = t(:edit)
           | &nbsp;
           = t(:page)

       == render 'form'

       => link_to 'Show', @carousel
       '|
       =< link_to 'Back', carousels_path

app/views/carousels/index.html.slim
div class="container"
  div class="col-lg-12"
     div class="bs-docs-section clearfix"
       div class="col-lg-12"
        div class="page-header"
         div class="col-lg-12"
            h1
              = t(:carousels)
              | :
            = link_to t(:new_carousel), new_carousel_path
       div class="col-lg-12"
         div class="table-responsive"
          table class="table table-hover"
            thead
              tr
                th scope="col"
                  = t(:user)
                th scope="col"
                  = t(:image)
                th scope="col"
                  = t(:page)
                th scope="col"
                  = t(:active)
                th
                th
                th

            tbody
              - @carousels.each do |carousel|
                tr class="table-primary"
                  td scope="row"
                    = carousel.user.name
                  td = image_tag carousel.image.url(:thumb), class: 'img-responsive'
                  td = carousel.page.title
                  td = carousel.active
                  td = link_to t(:show), carousel
                  td = link_to t(:edit), edit_carousel_path(carousel)
                  td = link_to t(:destroy), carousel, data: { confirm: t(:are_you_sure) }, method: :delete

          br

          = link_to t(:new_carousel), new_carousel_path

app/views/carousels/new.html.slim
div class="container"
   div class="col-lg-12"
     div class="page-header"
       h2 class="display-3"
         = t(:add)
         | &nbsp;
         = t(:carousel)
     == render 'form'

     = link_to 'Back', carousels_path

app/views/carousels/show.html.slim
div class="container"
   div class="col-lg-12"
     div class=""
       - if notice
          div class="alert alert-dismissible alert-danger"
            button type="button" class="close" data-dismiss="alert"
              | &times;
            = notice

       p
         strong Header:
         = @carousel.header
       p
         strong Sentence:
         = @carousel.sentence
       p
         strong Link:
         = @carousel.link
       p
         strong Image:
         = image_tag @carousel.image.url(:medium), class: "img-responsive"
       p
         strong Page:
         = @carousel.page.title
       p
         strong Active:
         = @carousel.active

       => link_to t(:edit), edit_carousel_path(@carousel)
       '|
       =< link_to t(:back), carousels_path