config/routes.rb
Rails.application.routes.draw do


  resources :conversations, only: [:index,:create,:new] do
    resources :messages, only: [:index,:create]
  end

  get 'communities/:community/events' => 'events#index', as: 'community_events'
  get 'communities/:community_id/contacts/preview' => "contacts#preview", as: 'community_contact_preview'
  resources :badge_rules
  get 'badges/:uuid/claim' => "badges#claim", as: 'badge_claim'
  get 'badges/:uuid/qrcode' => "badges#qrcode", as: 'qrcode_badge'
  get 'badges/:id/assertion' => "badges#assertion", as: 'badge_assertion'
  resources :badges
  resources :attendees
  resources :tickets
  resources :ticket_types

  resources :notifications, only: [:index]
  get "events/:id/downloads" => "events#calendar_download", as: 'event_calendar_download'
  get "event/:year/:month/:day" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/:year/:month/:day/*anything" => "events#index", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
  get "event/badges/:event_id" => "badges#index", as: "event_badges"
  get 'privacy' => 'home#privacy',  :defaults => { :id => '2' }, as: 'privacy'
  get 'news/:id/edit' => 'news#edit'
  #get 'communities/:id/edit' => 'communities#edit'
  get 'news/:id/*anything' => 'news#show', as: 'news_custom'
  #get 'communities/:id/*anything' => 'communities#show', as: 'community_custom'
  get 'user/:id/*anything' => 'user#show', as: 'user_custom'
  get 'users/:id/badges' => 'user#assertions', as: 'user_badges'
  get 'users/events' => 'user#events', as: 'my_events'

  post 'events/:id/unique' => 'events#unique', as: 'unique_event'
  post 'events/unique' => 'events#unique', as: 'new_unique_event'
  post 'events/:event_id/attendees/draw' => 'attendees#draw', as: 'draw_attendees'

  resources :events do
    resources :attendees, only: [:index]
    resources :schedule, only: [:index]
  end
  resources :user, only: [:show]
  resources :communities do
    resources :members
    resources :invites
    resources :boards do
      resources :board_messages, only: [:new,:edit,:show,:update,:create,:destroy]
    end
    resources :contacts
  end
  resources :carousels
  resources :pages
   mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :news
  get 'home/index'

  devise_for :users,  :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/shared/_badge.html.slim
div class="col-lg-2"
  = image_tag @badge.image.url, size: "90x90"

app/views/shared/_carousel.slim
div class="container"
  div class="splash"
    div class="row"
     | &nbsp;
     div id="myCarousel" class="carousel slide"
      div class="carousel-inner"
        - count=0
        - @page.carousels.each do |row|
          - item_class = count==0 ? {class: "item active"} : {class: "item"}
          div *item_class
            - count=1
            = image_tag row.image.url(:carousel), class: "img-responsive"
            div class="container"
              div class="carousel-caption"
                h1 = row.header
                p class="lead"
                  = row.sentence
                - unless row.link.empty?
                  = link_to t(:goto), row.link, class: "btn btn-lage btn-primary"
        a class="left carousel-control" href="#myCarousel" data-slide="prev"
          | &nbsp;
        a class="right carousel-control" href="#myCarousel" data-slide="next"
          | &nbsp;

app/views/shared/_footer.slim
    #footer
      .container
        .row
          .col-lg-12.icons
            .block
              ul.list-inline.text-center
                li.list-inline-item
                  a href="https://www.instagram.com/flosspanama" target="_blank"
                    span.fa-stack.fa-lg
                      i.fa.fa-circle.fa-stack-2x
                      i.fa.fa-instagram.fa-stack-1x.fa-inverse
                li.list-inline-item
                  a href="https://twitter.com/flosspa" target="_blank"
                    span.fa-stack.fa-lg
                      i.fa.fa-circle.fa-stack-2x
                      i.fa.fa-twitter.fa-stack-1x.fa-inverse
                li.list-inline-item
                  a href="https://www.facebook.com/flosspa" target="_blank"
                    span.fa-stack.fa-lg
                      i.fa.fa-circle.fa-stack-2x
                      i.fa.fa-facebook.fa-stack-1x.fa-inverse
                li.list-inline-item
                  a href="https://plus.google.com/communities/113233271634131928687" target="_blank"
                    span.fa-stack.fa-lg
                      i.fa.fa-circle.fa-stack-2x
                      i.fa.fa-google-plus.fa-stack-1x.fa-inverse
                li.list-inline-item
                  a href="https://gitlab.com/floss-pa" target="_blank"
                    span.fa-stack.fa-lg
                      i.fa.fa-circle.fa-stack-2x
                      i.fa.fa-gitlab.fa-stack-1x.fa-inverse
                li.list-inline-item
                  a href="https://t.me/flosspa" target="_blank"
                    span.fa-stack.fa-lg
                      i.fa.fa-circle.fa-stack-2x
                      i.fa.fa-telegram.fa-stack-1x.fa-inverse
          .col-lg-12.links
            ul.list-unstyled
              li.pull-right
                a href="https://floss-pa.net/#top"  Regresar al principio
              li
                a href="https://floss-pa.net/privacy"  Politicas de Privacidad

app/views/shared/_header.html.slim
div class="container"
 div class="row"
  div class="navbar-header"
    a href="../" class="navbar-brand"  = image_tag "logo.png", alt: "floss-pa", class: "img-fluid"
    button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main"
      span class="icon-bar"
      span class="icon-bar"
      span class="icon-bar"

  div  class="navbar-collapse collapse" id="navbar-main"
    ul class="nav navbar-nav"
      li = link_to t(:news), news_index_path
      li = link_to t(:communities), communities_path
      li = link_to t(:events), events_path
      li = link_to t(:badges), badges_path
      li = link_to "Wiki", "https://wiki.floss-pa.net/",{:target=>"_blank"}

    ul class="nav navbar-nav navbar-right"

      - unless user_signed_in?

        li = link_to t(:sign_up), new_user_registration_path
        li = link_to t(:sign_in), new_user_session_path

      - else

        - if current_user.has_role? :admin

          li class="dropdown"
            a class="dropdown-toggle" data-toggle="dropdown" href="#" id="user"
              | Admin
              span class="caret"
            ul class="dropdown-menu" aria-labelledby="user"
             li = link_to t(:pages), pages_path
             li = link_to t(:carousel), carousels_path
             li = link_to t(:badge_rules), badge_rules_path

        li class="dropdown"
          a class="dropdown-toggle" data-toggle="dropdown" href="#" id="actions"
            = t(:create)
            span class="caret"
          ul class="dropdown-menu" aria-labelledby="actions"
            li
              = link_to new_news_path do
                i class="fa fa-newspaper-o"
                | &nbsp;
                = t(:news)
            li
              = link_to new_community_path do
                i class="fa fa-group"
                | &nbsp;
                = t(:community)
            li
              = link_to new_event_path do
                i class="fa fa-calendar"
                | &nbsp;
                = t(:event)
        li class="dropdown"
          a class="dropdown-toggle" data-toggle="dropdown" href="#" id="conversations"
            span class="glyphicon glyphicon-comment"
            span class="badge"  id="unread-count-conversation"
             | 0
             / Notification.unread.where("recipient_id=?",current_user.id).count
            span class="caret"
          ul class="dropdown-menu" arial-labelledby="notifications" id="conversations-items"
            li class="dropdown-header text-uppercase"
              = t(:messages)
            - unless current_user.conversations.empty?
              li
                p.text-center.small = t(:no_new_comversations)
            li class="dropdown-divider"
            li class="dropdown-item"
              = link_to t(:all_conversations), conversations_url, class: "text-capitalize"
        li class="dropdown"
          a class="dropdown-toggle" data-toggle="dropdown" href="#" id="notifications"
            span class="glyphicon glyphicon-bell"
            span class="badge"  id="unread-count"
             | 0
             / Notification.unread.where("recipient_id=?",current_user.id).count
            span class="caret"
          ul class="dropdown-menu" arial-labelledby="notifications" id="notification-items"
            li class="dropdown-header text-uppercase"
              = t(:notification)
            - unless current_user.notifications.unread.empty?
              li
                p class="text-center small" id="notifications_empty"
                  = t(:no_new_notifications)


        li class="dropdown"
          a class="dropdown-toggle" data-toggle="dropdown" href="#" id="user"
            - if current_user.avatar.blank?
              = current_user.name
            - else
              = image_tag current_user.avatar.url(:thumb), alt: current_user.name, class: "img-circle", height: 20
            span class="caret"

          ul class="dropdown-menu" aria-labelledby="user"
            / li = link_to t(:profile), user_path(current_user)
            / li = link_to t(:edit) + ' ' + t(:profile), edit_user_path(current_user)
            li
              = link_to edit_user_registration_path do
                i class="fa fa-user-secret"
                | &nbsp;
                = t(:account)
            li
              = link_to user_custom_path(current_user,current_user.name) do
                i class="fa fa-user-o"
                | &nbsp;
                = t(:my_perfil)
            li
              = link_to my_events_path do
                i class="fa fa-calendar"
                | &nbsp;
                = t(:manage_events)
            li
              = link_to destroy_user_session_path, {:method=>"delete", :id=>"logout"}
                i class="fa fa-sign-out"
                | &nbsp;
                = t(:sign_out)